### ISSUE TITLE
Store Blockchain Workbench messages in Cosmos DB code does not work

### ISSUE THREAD

**Issue by HowardEdidin** [Azure-Samples/blockchain#10]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [ x] bug report -> please search issues before submitting
- [ ] feature request
- [X ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
> I followed the docs and created the Cosmos DB account and Function App. 

### Any log messages given by the failure
>2018-05-25T00:50:07.630 [Error] Exception while executing function: Functions.CosmosDBConsumer. mscorlib: Exception has been thrown by the target of an invocation. f-CosmosDBConsumer__-1449330061: Object reference not set to an instance of an object.

### Expected/desired behavior
>

### OS and Version?
> Windows 7, 8 or 10. Linux (which distribution). macOS (Yosemite? El Capitan? Sierra?)

### Versions
>

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by mmercuri** [comment]
Howard - I've reached out to the CosmosDB dev that put together the sample and will follow up.

**Comment by HowardEdidin** [comment]
I figured it out.  The test sample that was generated did not contain the operation
