### ISSUE TITLE
Digital Locker - 2 issues in sol file

### ISSUE THREAD

**Issue by rizzeeb** [Azure-Samples/blockchain#100]
There are two issues with the current digitallocker.sol file which caused the contact not to be accepted in workbench:
1) Spelling issue - currently this is how the line looks like in the contract: ContractUpdated("UploadDocments");  the word Documents is misspelt - it should be corrected to ContractUpdated("UploadDocuments");
2) Incorrect contract name - currently this is how the line looks like in the contract: ContractUpdated("AvailableToShare") - it should be corrected to ContractUpdated("ReleaseLockerAccess");

I made the 2 changes in my local copy and was able to execute the application...

**Comment by ali92hm** [comment]
@rizzeeb Thank you for reporting this issue, you are correct. I've fixed the files.

Starting workbench 1.6.0 (should be released in January) you do not need to explicitly call ContractUpdated anymore
