### ISSUE TITLE
DevOps - deploy to Workbench

### ISSUE THREAD

**Issue by ygizhitsa** [Azure-Samples/blockchain#103]
DevOps does not have an example deploying blockchain application to the workbench

**Comment by qishangg** [comment]
Hi there,

Please find documentation [here](https://docs.microsoft.com/en-us/azure/blockchain/workbench/deploy).

Thanks!

**Comment by brendalee** [comment]
To deploy a blockchain application to Workbench, follow instructions [here ](https://docs.microsoft.com/en-us/azure/blockchain/workbench/create-app#add-blockchain-application-to-blockchain-workbench). Thanks!

**Comment by ygizhitsa** [comment]
That is a description for Manual process , for the blockchain  user in the Administrative Role. The issue I have opened is DevOps related. The deployment is unattended,, automated , from source control to blockechain workbench in context of service account (aka azure principal)  . The documentation you refer is not for that. The link I put in my response does, but it targets ganache and not covering ABW. Please re-open issue - it is not closed
