### ISSUE TITLE
Ping pong smart contract can't be deployed on Workbench

### ISSUE THREAD

**Issue by mjtpena** [Azure-Samples/blockchain#108]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
```

### Minimal steps to reproduce
> Upload the following solidity file:
https://github.com/Azure-Samples/blockchain/tree/master/blockchain-workbench/application-and-smart-contract-samples/ping-pong-game/ethereum

### Any log messages given by the failure
> See image:
<img width="610" alt="screenshot 2019-01-08 17 18 01" src="https://user-images.githubusercontent.com/19221213/50813153-955e7480-1369-11e9-93bb-b6f4fae97970.png">

### Expected/desired behavior
> The solidity file should be uploaded.

### OS and Version?
> macOS (High Sierra)

### Versions
> Workbench 1

**Comment by brendalee** [comment]
Hi, it looks like you're on an older version of Workbench. Please deploy or upgrade to version 1.6.0 and these errors should be resolved. Thanks!
