### ISSUE TITLE
Coffee .sol file needs to be updated

### ISSUE THREAD

**Issue by danielnorkin** [Azure-Samples/blockchain#114]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [x ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
>load workbench with the current coffee.sol file

### Any log messages given by the failure
>
Error: Workflow contract Coffee should not derive from WorkbenchBase base contract. This is considered an error now. Update the Coffee contract to remove WorkbenchBase and calls to "ContractCreated" and "ContractUpdated" functions.

Warnings: 
Coffee.sol:10:5: Warning: Defining constructors as functions with the same name as the contract is deprecated. Use "constructor(...) { ... }" instead. function WorkbenchBase(string applicationName, string workflowName) internal {
 ^ (Relevant source part starts here and spans across multiple lines).
Coffee.sol:63:5: Warning: Defining constructors as functions with the same name as the contract is deprecated. Use "constructor(...) { ... }" instead. function Coffee(string description, address device, address supplyChainOwner, address supplyChainObserver, int minHumidity, int maxHumidity, int minTemperature, int maxTemperature) public {
 ^ (Relevant source part starts here and spans across multiple lines).
Coffee.sol:16:9: Warning: Invoking events without "emit" prefix is deprecated. WorkbenchContractCreated(ApplicationName, WorkflowName, msg.sender);
 ^-----------------------------------------------------------------^
Coffee.sol:20:9: Warning: Invoking events without "emit" prefix is deprecated. WorkbenchContractUpdated(ApplicationName, WorkflowName, action, msg.sender);
 ^-------------------------------------------------------------------------^

### Expected/desired behavior
>should load with no issues

### OS and Version?
> workbench 1.6

### Versions
>

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by ali92hm** [comment]
It seems like a PR was merged to solve this issue
