### ISSUE TITLE
Blockscout UI won't render after following instructions

### ISSUE THREAD

**Issue by jalextowle** [Azure-Samples/blockchain#117]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
>
Follow the steps from https://github.com/Azure-Samples/blockchain/tree/master/ledger/template/ethereum-on-azure/technology-samples/blockscout. I used the Private IP address of one of the nodes in the blockchain consortium that I had previously set up. 

### Any log messages given by the failure
>

502 Bad Gateway. 

### Expected/desired behavior
>

The blockscout UI should render when I navigate to the IP address from the deployment. 

### OS and Version?
> Windows 7, 8 or 10. Linux (which distribution). macOS (Yosemite? El Capitan? Sierra?)

Ubuntu 16.04 LTS. 

### Versions
>

### Mention any other details that might be useful

I have tried several different IP addresses for the node from the consortium. Additionally, lot's of warnings appear when `install_blockscout.sh` is run. I didn't install any dependencies before running this script, so I may be missing something. 

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by acravenho** [comment]
I'll create a PR with an updated script this week.
