### ISSUE TITLE
“List Item to Sell” not creating a new contract in in the Item Listing workflow

### ISSUE THREAD

**Issue by tanjara** [Azure-Samples/blockchain#121]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [x ] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
>
1.	Deploy Bazaar - Item Listing Sample Application
2.	Login as Bazaar Maintainer and add new contract to the Bazaar workflow
3.	Login as Party and take action “List Item to Sell” in the contract created in step 2
4.	The action is recorded, but there is no new contract in the Item Listing workflow 

### Any log messages given by the failure
> No

### Expected/desired behavior
> There is a new contract in the Item Listing workflow

### OS and Version?
> Windows 10

### Versions
>

### Mention any other details that might be useful

> ---------------------------------------------------------------
The code 
currentItemListing = new ItemListing(itemName, itemPrice, CurrentSeller, CurrentContractAddress, InstancePartyA, InstancePartyB); 

does not create a new contract. I found no new contracts in the database. 
> Thanks! We'll be in touch soon.

**Comment by ali92hm** [comment]
Hi there,

Can you please specify which version of Workbench you are running? Also if you've upgraded which version of Workbench was originally deployed.

We've seen this issue with Workbench < 1.3 since there was a bug in the Parity client. Unfortunately, our upgrade script does not upgrade the parity
