### ISSUE TITLE
ServiceBus to Blockchain connection not working (when using existing Blockchain) 

### ISSUE THREAD

**Issue by rizzeeb** [Azure-Samples/blockchain#122]
When I push a message through the ServiceBus to the Blockchain, the event does not seem to get to the Blockchain - this is only true if instead of creating a new Blockchain (when I create the Workbench resource), I use an existing Blockchain (i.e. I use the Azure template to create a PoA ethereum resource and then associate that endpoint to the Workbench Template).  I'm leveraging the latter so I can then use explorer like blk.io to view the blocks, contracts, transactions on the blockchain...

**Comment by brendalee** [comment]
That's strange - are you getting any error messages as documented here: https://docs.microsoft.com/en-us/azure/blockchain/workbench/messages-overview#input-api-error-codes-and-messages

**Comment by ramyapradhan** [comment]
Hello @rizzeeb, since it is getting close to a year since we have heard from you, we are going ahead and closing this issue.  Please feel free to reach out if you are still having issues.  
Thank you!
