### ISSUE TITLE
Create Contract JSON not working V1.6 Workbench...

### ISSUE THREAD

**Issue by rizzeeb** [Azure-Samples/blockchain#123]
Create Contract Request JSON similar to this does not work when sent via ServiceBus (https://bit.ly/2sDWzUv)..I am able to create a contract using the REST API using a very different JSON (https://bit.ly/2RUYz9a). BTW - I'm able to update the contract using ServiceBus using a variation of the below (the sample given in the documentation), just the Create Contract is does not work...

{ 
    "requestId": "ce3c429b-a091-4baa-b29b-5b576162b211", 
    "userChainIdentifier": "0x9a8DDaCa9B7488683A4d62d0817E965E8f248398", 
    "applicationName": "AssetTransfer", 
    "workflowName": "AssetTransfer", 
    "parameters": [ 
        { 
            "name": "description", 
            "value": "a 1969 dodge charger" 
        }, 
        { 
            "name": "price", 
            "value": "12345" 
        } 
    ], 
    "connectionId": 1, 
    "messageSchemaVersion": "1.0.0", 
    "messageName": "CreateContractRequest" 
}

**Comment by keikumata** [comment]
Hi @rizzeeb thanks for using Workbench!

What is the error that you receive back after submitting the CreateContractRequest message on ServiceBus? Would you happen to have multiple versions enabled for this specific application? 

Also, we've created a troubleshooting guide that can sometimes help us pinpoint exactly what the error is ([link to the guide](https://github.com/Azure-Samples/blockchain/blob/master/blockchain-workbench/faq/troubleshooting.md)). To obtain the RequestId necessary to use the troubleshooting guide, you would need to go to your Workbench website and find that contract action. If there was an error then there would be text giving you a RequestId.

**Comment by rizzeeb** [comment]
Thanks.. The sending program just waits for a response, since nothing comes back from the workbench.  Since there is no action taken by the workbench, there is no request ID on the workbench, I'm familiar with the guide you reference above and have used the request ID in  looking at the Workbooks when I see a request ID in workbench, but nothing for this scenario,  I also created a logicApp and am subscribing to ServiceBus and EventGrid to capture the information and from looking at the messages from the egress queue (through above and from ServicebusExplorer), and performing timing correlation it seems like the error may be Error code 4000: CreateContractRequest deserialization failed, specifically this is the message I see in the egress queue: 
{
  "ContractId": null,
  "ContractLedgerIdentifier": null,
  "RequestId": "f9c369fd-dedb-4b35-aa3a-793ccba0d058",
  "ConnectionId": 1,
  "Status": "Error",
  "AdditionalInformation": {
    "ErrorCode": 4000,
    "ErrorMessage": "CreateContractRequest deserialization failed"
  },
  "MessageSchemaVersion": "1.0.0",
  "MessageName": "CreateContractUpdate"
}

**Comment by brendalee** [comment]
Hi rizeeb, try to add a Version number and see if that helps.

**Comment by rizzeeb** [comment]
@brendalee - the JSON already has the version number - "MessageSchemaVersion": "1.0.0" - did you want me to send a separate field? Can you send me the sample message, that you believe will work?

**Comment by dnyandeobharambe** [comment]
I am getting similar error, for me I added version and my contract looks like below
{ 
    "requestId": "ce3c429b-a091-4baa-b29b-5b576162b211", 
    "userChainIdentifier": "0x9a8DDaCa9B7488683A4d62d0817E965E8f248398", 
    "applicationName": "AssetTransfer",
    "version": "1.0",
    "workflowName": "AssetTransfer", 
    "parameters": [ 
        { 
            "name": "description", 
            "value": "a 1969 dodge charger" 
        }, 
        { 
            "name": "price", 
            "value": "12345" 
        } 
    ], 
    "connectionId": 1, 
    "messageSchemaVersion": "1.0.0", 
    "messageName": "CreateContractRequest" 
}

now when I check application insight I get following information. I am not sure why it giving me this error. Can you please help me to understnd

Sending message {"ContractId":null,"ContractLedgerIdentifier":null,"RequestId":"c4c2e955-b6f6-47d4-b7bc-45868ba40427","ConnectionId":1,"Status":"Error","AdditionalInformation":{"ErrorCode":4000,"ErrorMessage":"UserChainIdentifier 1 does not exist."},"MessageSchemaVersion":"1.0.0","MessageName":"CreateContractUpdate"} on egressTopic.	

Completed processing message; elapsed: 00:00:00.425685

**Comment by dnyandeobharambe** [comment]
I am able to fix above error .The stored procedure you recommended in sample itself is incorrect. It is trying to to select cc.LedgerId
as
 ChainId

but it should be Chianidentifier from Userchainmapping. It means probably stored procedure need additional joins to

fetch that values.

**Comment by brendalee** [comment]
Thanks all for your patience and for sharing your learnings.  Closing this issue
