### ISSUE TITLE
An image file on azure-blob-storage document is broken

### ISSUE THREAD

**Issue by owlworks** [Azure-Samples/blockchain#128]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
- [x] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
>Access this readme url: https://github.com/Azure-Samples/blockchain/tree/master/blockchain-development-kit/accelerators/attestable-documents-and-media/blockchain-workbench/azure-blob-storage
> A screenshot under "Choose a name for the Function App..." may be broken. I cannot see full image.

### Any log messages given by the failure
> no error message

### Expected/desired behavior
> Show full screenshot

### OS and Version?
> OS X sierra, chrome
 
### Versions
> 1.6.0

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by brendalee** [comment]
Thanks for letting us know. @cnsegura do you mind taking a look at this?
