### ISSUE TITLE
Smart contracts functions with return values

### ISSUE THREAD

**Issue by mikedennis** [Azure-Samples/blockchain#13]
Is there a way of modeling contract functions with return values in the configuration? I did not see this mentioned in the docs anywhere and all the samples don't have return values in the contract functions.

**Comment by mmercuri** [comment]
There is not at this time. The model for workbench is to deliver state back to properties that are exposed within the contract when you want to display them in the UX.

If you want to use functions with returns outside of the UI - intra-contract or contract-contract , don't include them in the config and they should work fine.
