### ISSUE TITLE
Adding/Removing consortium member

### ISSUE THREAD

**Issue by ygizhitsa** [Azure-Samples/blockchain#139]
- [ ] bug report -> please search issues before submitting
- [x] feature request
- [x] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)

Please, provide guided example of adding consortium member to the consortium and separating consortium member without assets lost on both sides.

**Comment by brendalee** [comment]
We have docs on how to manage members in Workbench here: https://docs.microsoft.com/en-us/azure/blockchain/workbench/manage-users

**Comment by ygizhitsa** [comment]
@brendalee managing member and  managing consortium member two different things. Document you have provided do not apply.

**Comment by ygizhitsa** [comment]
@brendalee  please re-open. Do not want to create a new ticket
