### ISSUE TITLE
Restoring ABW with existing blockchain  infrastructure

### ISSUE THREAD

**Issue by ygizhitsa** [Azure-Samples/blockchain#140]
- [ ] bug report -> please search issues before submitting
- [x] feature request
- [x] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)

Please, provide guided example of restoring ABW with existing blockchain  infrastructure

**Comment by brendalee** [comment]
You can connect to an existing blockchain network via the "bring your own blockchain" feature at deployment time. You can find more details in the deployment documentation: https://docs.microsoft.com/en-us/azure/blockchain/workbench/deploy

**Comment by ygizhitsa** [comment]
@brendalee document is very generic and focuses on the creating the ABW. I have asked for guided example focused only  on the Restoring ABW and way to restore previous information in the ABW persistent endpoints,, keys and other securables already shared with Consortium members .

 Please, re-open the ticket
