### ISSUE TITLE
 Recovering Blockchain , by replaying recorded transactions from the ABW off-chain storages (SQL or Blob)

### ISSUE THREAD

**Issue by ygizhitsa** [Azure-Samples/blockchain#141]
- [ ] bug report -> please search issues before submitting
- [x] feature request
- [x] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)

Please, provide guided example of Recovering Blockchain , by replaying recorded transactions from the ABW off-chain storages (SQL or Blob)

**Comment by brendalee** [comment]
We currently don't have a feature to replay the recorded transactions from the database.

For details on Workbench database views, you can see them here: https://docs.microsoft.com/en-us/azure/blockchain/workbench/database-views

**Comment by brendalee** [comment]
You can put in feature requests at https://aka.ms/blockchainuservoice
