### ISSUE TITLE
Device users cannot see their Apps after IoT integration is done

### ISSUE THREAD

**Issue by rulopotamo** [Azure-Samples/blockchain#145]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [X ] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
>I created an AWB and uploaded the Refrigerated Transportation App. It tested correctly. I could have all actors perform their actions
  I created the IoT Hub and also tested that it was working (i.e. receiving data from both a simulated raspberry and an Android app)
I then followed the tutorial for passing messages from IoT Hub to ABW, by creating the logic app and modifying the BC database to store the proper devices names.
Upon testing the Logic App worked properly (meaning all steps cleared) 
Then I created a new contract on the Refrigerated Transportation App. Now, a **No Applications Were Found** message appeared for the Device Users, this is, even when a Device User was added to the contract, no apps appeared listed when logged as the Device User.

### Mention any other details that might be useful
I suspected the name change on the database could be responsible, since the App was created _before_ the change in the database. Could that be the issue?
So I deleted the app (directly from the database table, forcing all constraints off) and created a new version. Unfortunately, attempts to create a new contract now yield a **the action failed. Please check your input or code...** error. 

I could create a new version of the app with a different name, but I'm afraid that would break the logic app. 

So, any hints about the possible issues before I give up and just deploy a fresh version of the Workbench?

Cheers

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by ramyapradhan** [comment]
Hello @rulopotamo, the change is the database could be a potential cause.  We would recommend deploying a fresh version of Workbench.  Please let us know how that goes and please also do let us know on the ways in which we can help.

Thank you!

**Comment by ramyapradhan** [comment]
Hello @rulopotamo, I am writing to inform you that I will be closing this issue since it has been open for a year today.  Please feel free to re-open this issue if needed.
Thanks :)
Ramya
