### ISSUE TITLE
Restoring ABW with existing blockchain infrastructur - #140 (was not addressed)

### ISSUE THREAD

**Issue by ygizhitsa** [Azure-Samples/blockchain#147]
bug report -> please search issues before submitting
 
 feature request
 
 documentation issue or request
 
 regression (a behavior that used to work and stopped in a new release)
Please, provide guided example of restoring ABW with existing blockchain infrastructure

Problem with previous response

Answer to #140 
You can connect to an existing blockchain network via the "bring your own blockchain" feature at deployment time. You can find more details in the deployment documentation: https://docs.microsoft.com/en-us/azure/blockchain/workbench/deploy ( responder completely missing the point)

What is wrong with an answer 
@brendalee document you are referring to is very generic and focuses on the creating the ABW. I have asked for guided example focused only on the Restoring ABW and way to restore previous information in the ABW persistent endpoints,, keys and other securables already shared with Consortium members .

Also, for the ABW team. I think, by now blockchain developers see  a lot of value in the blockchain. However, business would not take it seriously until blockchain management aspects are not addressed.

Especially, such as DR and consortium management

**Comment by ali92hm** [comment]
@ygizhitsa I completely understand what feature what you are asking for. We have thought about this, and we have an item on the backlog but this item is not currently prioritized.

We would like to understand your scenario for back-fill more, could you please share your scenario?

I also understand what you're asking on DR and consortium management, the good news is we are actively working on that :)

**Comment by ramyapradhan** [comment]
Hello @ygizhitsa, thank you for taking the time and suggesting this feature. We are closing this issue since a feature request item for this has been added to our backlog.
