### ISSUE TITLE
UI does not update automatically

### ISSUE THREAD

**Issue by laszlomoricz** [Azure-Samples/blockchain#15]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [ X] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ X] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
> Simply interact with a contract via the UI

### Any log messages given by the failure
> no

### Expected/desired behavior
> Using the Blockchain Workbench UI: when a user toke an action using any contract, the other party does not get prompted for taking an action without refreshing the page in the browser. It used to work as expected a couple of days ago.

### OS and Version?
> Windows 10, Google Version 67.0.3396.87 (Official Build) (64-bit)

### Versions
>

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by brendalee** [comment]
What version of Workbench are you on?

**Comment by brendalee** [comment]
Closing this as this should be fixed now. Let us know if you still run into this problem.
