### ISSUE TITLE
Incorrectly uploaded images

### ISSUE THREAD

**Issue by abethencourt** [Azure-Samples/blockchain#154]
Hello,

Just letting you know the images uploaded on https://github.com/Azure-Samples/blockchain/tree/master/blockchain-development-kit/accelerators/attestable-documents-and-media/blockchain-workbench/azure-blob-storage have failed to fully upload completely and only part of them are displayed. You should re-upload them.

**Comment by brendalee** [comment]
Thanks! FYI - @cnsegura
