### ISSUE TITLE
Hello-Blockchain Authentication Error

### ISSUE THREAD

**Issue by MarinPopescu** [Azure-Samples/blockchain#155]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
- [ x ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce

I installed the hello-blockchain application. By using it's API link, it works fine but I am trying to create and execute contracts programmatically using the API
In the Authentication/Authorization tab, I set the App Service Authentication On and I selected from the dropdown 'Log in with Azure Active Directory'
I then followed [this ](https://docs.microsoft.com/en-us/azure/blockchain/workbench/deploy#blockchain-workbench-web-url) and [this]( https://docs.microsoft.com/en-us/azure/blockchain/workbench/deploy#blockchain-workbench-web-url)
documentation to setup my application but when I try to execute a simple GET request on the API, the result is always 401 

I went through this process step by step with the Microsoft support team via a conference call.
They have also tried to simulate this process on their own without success confirmed by both the team I've been speaking to and the Microsoft Success Manager
Can someone assist us with this authentication problem?
I've also posted a question [here](https://github.com/Azure-Samples/blockchain/issues/134)

### Any log messages given by the failure
401

### OS and Version?
> Windows 7

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by ali92hm** [comment]
@MarinPopescu that is the expected behavior, We do not use the App Service Authentication. The authentication is enabled in our code itself.

Please take a look at this [article](https://github.com/Azure-Samples/blockchain/tree/master/blockchain-workbench/scripts/workbench-serviceprincipal) and look at these [samples](https://github.com/Azure-Samples/blockchain/tree/master/blockchain-workbench/auth-samples) to see how to use the API programmatically.

**Comment by MarinPopescu** [comment]
@ali92hm I switched the App Service Authentication off and it failed as well. The reason why I had it switched on is because that's what I did with the Microsoft support team a while back. 

Yesterday, I've been following [this](https://github.com/Azure-Samples/blockchain/tree/master/blockchain-workbench/auth-samples/postman-user) tutorial and I received a Token, but that still returned me 401 when I executed a basic GET request. 

At the moment I am trying to follow, I assume your [tutorial](https://medium.com/@malirezaie/how-to-enable-programmatic-interaction-with-azure-blockchain-workbench-apis-56c0d95c79c0), in parallel with the Microsoft [documentation](https://docs.microsoft.com/en-us/azure/blockchain/workbench/deploy). I removed all my previous work and started it from scratch. 

The problem I am facing right now is at [this](https://docs.microsoft.com/en-us/azure/blockchain/workbench/deploy#modify-manifest) step where I can not update the manifest file, I am getting the error 'Failed to update application Blockchain API. Error details: Request_BadRequest'. I've been trying to solve it using [this](https://social.msdn.microsoft.com/Forums/sqlserver/en-US/a21166d1-4ae5-4743-b9d3-a26b7468cb1a/error-when-uploading-updated-application-manifest?forum=WindowsAzureAD) post, but it doesn't work either. 

I am not sure if it is because of the problem above or not, but I can also not find my API in the 'Required permissions' Select an API tab.

**Comment by p0onage** [comment]
Check out my recent Microsoft forum post @MarinPopescu to locally get the swagger endpoint working 

https://social.msdn.microsoft.com/Forums/en-US/f603e835-0ebb-453e-ae00-60319371b10b/swagger-api?forum=azureblockchain

**Comment by ali92hm** [comment]
@MarinPopescu If granting permission fails to your Application Registration then that means you don't have the required permission in your AAD tenant

**Comment by MarinPopescu** [comment]
@ali92hm I thought that would be the case, we changed the permissions and I was able to grant permissions. I used postman with the bearer token authentication to send a simple get request and that seems to work fine, I think this is solved now. Thank you both for the support.
