### ISSUE TITLE
Was SharePoint integration example deleted?

### ISSUE THREAD

**Issue by MauSOliveira** [Azure-Samples/blockchain#168]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
- [X] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
> Try to navigate to the URL https://github.com/Azure-Samples/blockchain/tree/master/blockchain-development-kit/accelerators/attestable-documents-and-media/blockchain-workbench/sharepoint

### Any log messages given by the failure
> HTTP 404 Error 

### Expected/desired behavior
> Access to the sample provided on https://msdn.microsoft.com/magazine/mt833290

### OS and Version?
> Windows 10.0.17134.523

### Versions
>

### Mention any other details that might be useful
> Hi, guys! Please, restore the example presented in this amazing MSDN Magazine article: https://msdn.microsoft.com/magazine/mt833290. Thanks in advance!

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by MauSOliveira** [comment]
It seems to be moved. I've found it in another path: https://github.com/Azure-Samples/blockchain-devkit/tree/master/accelerators/attestable-documents-and-media/blockchain-workbench/SharePoint
Please, close this issue. Thanks!

**Comment by ali92hm** [comment]
Yes, we moved the devkit to it's own repo
