### ISSUE TITLE
Automate app creation 

### ISSUE THREAD

**Issue by ygizhitsa** [Azure-Samples/blockchain#169]
- [ x] bug report -> please search issues before submitting
- [ x] feature request
- [ x] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)

### Minimal steps to reproduce
1.  Call Applications POST method
2. Try  to run PS snippet

### Any log messages given by the failure
>

### Expected/desired behavior
New application created by calling POST method

### OS and Version?
Windows 2016

### Versions
Latest

### Mention any other details that might be useful
Trying to automate creation of the application

1.Application, my understanding  consists of two files sol and json
Postman has only one parameter appFile. Please suggest 

2.Looking into a swagger page, I think headers in the postman either not complete or wrong. I have added  Content-Type":"multipart/form-data" and  "Accept":"text/html. Status – still doesn’t work

3.  I have created following powershell block which does not work. Please suggest. Also, what would be a proper way to make file path relative to the ps script location 
  Write-Output '################### CALL AN APP ###################################'
#Making bc call
$prefix='bchal-wly2wp'
$bcUri = 'https://' + $prefix +'-api.azurewebsites.net/api/v1/applications'
$bcUri

   $bchdrs = @{}
   $bchdrs.Add("Authorization",$bearer_token)
   $bchdrs.Add("Content-Type","multipart/form-data")
   $bchdrs.Add("Accept","text/html")
   $bchdrs.Add("control","no-cache")
   $bchdrs

$bresponse= Invoke-RestMethod -Uri $bcUri  -Method Post -Headers $bchdrs  -Infile "C:\projects\ps\az\BasicProvenance.json"
$bresponse
 
4. Also, what would be Azure DevOps snippet for the invocation?
I came up with following, but it doesn’t work and I’m not sure how to provide parameters to a script including file used to in the post

task: PowerShell@2
  displayName: 'Create ABW application PowerShell Script'
  inputs:
    targetType: 'filePath'
    filePath: '$(Build.SourcesDirectory)\abw\CreateABWApplication.ps1'
    arguments: -BumpBuild -BuildNumber:$(Build.BuildId)
    parameters : ? and reference to json and sol files in the build directories

**Comment by ramyapradhan** [comment]
Hello @ygizhitsa, 

I believe I have provided a solution to this question in my reply to issue 210 (https://github.com/Azure-Samples/blockchain/issues/210).  As this issue is tracked there, I am closing this issue.  Please feel free to re-open this if needed.

Thanks,
Ramya
