### ISSUE TITLE
Buy option not available after item listed. in bazar item listing.

### ISSUE THREAD

**Issue by swapnilmalap** [Azure-Samples/blockchain#17]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
>

### Any log messages given by the failure
>

### Expected/desired behavior
>

### OS and Version?
> Windows 7, 8 or 10. Linux (which distribution). macOS (Yosemite? El Capitan? Sierra?)

### Versions
>

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by brendalee** [comment]
The buy option shows up in the Item Listing workflow. Go back to the Bazaar Item Listing workflows and drill down into the Item Listing Workflow to double check.
