### ISSUE TITLE
To leave trace use Chrome for bowser not Edge if you cannot add member to HelloWorld Blockchain that is asking Admin right on Azure AD even after your organisation admin has grant you right ?

### ISSUE THREAD

**Issue by mcousine** [Azure-Samples/blockchain#175]
If you have complete the hole Azure AD Setup when deploying Azure Blockchain workbench and still have problem when trying to add member on a helloWolrd Blockchain example in this repo you need to switch browser to Chrome will not ask you to have admin Role on Azure AD when searching user. See step1-4 for problem

Step1
 [https://photos.app.goo.gl/ShvPRTLo6YdGawmm9](https://photos.app.goo.gl/ShvPRTLo6YdGawmm9)
Step2 
[https://photos.app.goo.gl/z5sMXX7DVvXPBpvr7](https://photos.app.goo.gl/z5sMXX7DVvXPBpvr7)
Step3 
[https://photos.app.goo.gl/wQrf1KcG9NUZrQ7S6](https://photos.app.goo.gl/wQrf1KcG9NUZrQ7S6)
Step4 Error ! with IE and Edge Chrome OK 
[https://photos.app.goo.gl/fQiBNqCmF3dECo6C6](https://photos.app.goo.gl/fQiBNqCmF3dECo6C6)

Similar problem issue.
[https://social.msdn.microsoft.com/Forums/en-US/26dcb544-b57f-4dd1-b15e-9cfaa389e429/blockchain-workbench-unable-to-add-user-to-app?forum=azureblockchain](https://social.msdn.microsoft.com/Forums/en-US/26dcb544-b57f-4dd1-b15e-9cfaa389e429/blockchain-workbench-unable-to-add-user-to-app?forum=azureblockchain)

[https://github.com/MicrosoftDocs/azure-docs/issues/9575](https://github.com/MicrosoftDocs/azure-docs/issues/9575)

**Comment by ramyapradhan** [comment]
Hello,

Please let us know if any of the solutions mentioned in that forum post's discussion helped.

Thanks.

**Comment by ramyapradhan** [comment]
Hello @mcousine, please let us know if you are still facing issues.

Thank you!

**Comment by ramyapradhan** [comment]
Hello @mcousine, 

I am writing to inform you that I will be closing this thread since this has been open for more than 30 days.  Please feel free to re-open it.

Thanks,
Ramya

**Comment by RyanMcgrane** [comment]
Followed all the prerequisites for deploying azure blockchain workbench and all documentation regarding graph API permissions and AD users and groups with Admin access. When in workbench still receiving the error below when trying to add a user into an application.
Error 403: Authorization_RequestDenied - Insufficient privileges to complete the operation.

All other forums and docs posted have been looked at =, but still has not fixed the issue. Any suggestions?
