### ISSUE TITLE
Logic App: Unable to use dynamic variables for "Execute smart contract function (incurring gas cost)"

### ISSUE THREAD

**Issue by StefH** [Azure-Samples/blockchain#180]
### This issue is for a:
```
- [x] bug report
```

### Minimal steps to reproduce
1. Create a Logic App

2. Define variables for ABI
![image](https://user-images.githubusercontent.com/249938/58013106-374f5400-7af6-11e9-97d2-7e77f8d54369.png)

3. Add the BlockChain : "Execute smart contract function (incurring gas cost)"
Use the ABI here:
![image](https://user-images.githubusercontent.com/249938/58013125-43d3ac80-7af6-11e9-884d-0691e09663ce.png)

4. Unable to define a function with parameters.

### Expected/desired behavior
> My function **setString** should be callable:
![image](https://user-images.githubusercontent.com/249938/58013207-71205a80-7af6-11e9-9217-87a24e342a4d.png)

**Comment by imnaseer** [comment]
This is a known limitation of the existing version of the connector. The ABI needs to be known at design time in order to select a function and specify its parameters.
