### ISSUE TITLE
Azure POA Blockscout setup 502 bad gateway

### ISSUE THREAD

**Issue by Chrissie** [Azure-Samples/blockchain#182]
I followed the Blockscout setup guide multiple times.

The web app is not starting, hence nginx is reporting 502 as error code on the web page.

Upon closer inspection I can see the systemctl blockscout.service restarting every few seconds.

Running the service command `mix phx.server` in ~/blockscout gives the following error, which I was not able to resolve.
```
** (Code.LoadError) could not load /home/VMadmin12345/blockscout/apps/block_scout_web/config/dev.secret.exs
    (elixir) lib/code.ex:1147: Code.find_file/2
    (elixir) lib/code.ex:706: Code.eval_file/2
    (mix) lib/mix/config.ex:187: anonymous fn/2 in Mix.Config.__import__!/2
    (elixir) lib/enum.ex:1940: Enum."-reduce/3-lists^foldl/2-0-"/3
    (mix) lib/mix/config.ex:186: Mix.Config.__import__!/2
    (stdlib) erl_eval.erl:680: :erl_eval.do_apply/6
    (elixir) lib/code.ex:232: Code.eval_string/3
```

**Comment by ali92hm** [comment]
Hey @Chrissie,

We are aware of the issue and are working to solve it. Thank you for opening this issue

**Comment by ali92hm** [comment]
I reverted back the changes that broke the script. Please give it another try and let us know.

**Comment by Chrissie** [comment]
Hi @ali92hm 

Thank you for your effort. Your change did indeed do 'something': The 502 disappeared.
Sadly it changed into a 500, the service is still crashing instantly. 
Running the install script install_blockscout.sh returned no errors.

The new error log on the service is this:

```
● blockscout.service - Blockscout Web App
   Loaded: loaded (/etc/systemd/system/blockscout.service; disabled; vendor preset: enabled)
   Active: failed (Result: start-limit-hit) since Wed 2019-05-29 23:09:15 UTC; 2s ago
  Process: 2993 ExecStart=/usr/local/bin/mix phx.server (code=exited, status=203/EXEC)
 Main PID: 2993 (code=exited, status=203/EXEC)

May 29 23:09:15 *machine* systemd[1]: blockscout.service: Main process exited, code=exited, status=203/EXEC
May 29 23:09:15 *machine* systemd[1]: blockscout.service: Unit entered failed state.
May 29 23:09:15 *machine* systemd[1]: blockscout.service: Failed with result 'exit-code'.
May 29 23:09:15 *machine* systemd[1]: blockscout.service: Service hold-off time over, scheduling restart.
May 29 23:09:15 *machine* systemd[1]: Stopped Blockscout Web App.
May 29 23:09:15 *machine* systemd[1]: blockscout.service: Start request repeated too quickly.
May 29 23:09:15 *machine* systemd[1]: Failed to start Blockscout Web App.
May 29 23:09:15 *machine* systemd[1]: blockscout.service: Unit entered failed state.
May 29 23:09:15 *machine* systemd[1]: blockscout.service: Failed with result 'start-limit-hit'.
```


Running mix phx.server in ~./blockscout gives the same error, which is the core of this issue.
```
mix phx.server
** (Code.LoadError) could not load /home/VMadmin12345/blockscout/apps/block_scout_web/config/dev.secret.exs
    (elixir) lib/code.ex:1147: Code.find_file/2
    (elixir) lib/code.ex:706: Code.eval_file/2
    (mix) lib/mix/config.ex:187: anonymous fn/2 in Mix.Config.__import__!/2
    (elixir) lib/enum.ex:1940: Enum."-reduce/3-lists^foldl/2-0-"/3
    (mix) lib/mix/config.ex:186: Mix.Config.__import__!/2
    (stdlib) erl_eval.erl:680: :erl_eval.do_apply/6
    (elixir) lib/code.ex:232: Code.eval_string/3
```

**Comment by ali92hm** [comment]
So we recommend using Ubuntu 16.04. Could you please give me more info about your environment/OS version so I can try to repro?

**Comment by Chrissie** [comment]
I tried it both in the setup described on the readme page and on a POA blockchain node (and mapped the port 80 of nginx to another port). Both solutions are delivering the same results/errors, so I think you can reproduce it easily.

**Comment by Chrissie** [comment]
I tried it both in the setup described on the readme page and on a POA blockchain node (and mapped the port 80 of nginx to another port). Both solutions are delivering the same results/errors, so I think you can reproduce it easily.
________________________________

**Comment by ali92hm** [comment]
I just setup a new instance of POA and setup blockscout on a separate Ubuntu **16.04 LTS** VM and everything seems to work properly.

One thing that comes to mind is the RPC and ws connection endpoints. Have you made sure that your RPC endpoint is the IP address associated with the load balancer and the port is `8540` and the ws endpoint is the address associated with **one of the VMS** and the port is `8547`

**Comment by Chrissie** [comment]
Because I do not want to run out of Azure credits I tried this on a fresh DigitalOcean droplet. 

Result: 502 Bad Gateway. One thing to note is that the POA setup is from April 28, and I do not want to set it up again to lose the existing contracts.

Setup command: 
`./install_blockscout.sh "http://<load balancer ip>:8540" "ws://<public ip of blockchain vm>:8547" "<Password>"`

The ports of the (jsonrpc and websockets) are open, also in the Azure resources (just the default settings). If you want the specific IP addresses you can send me an email. 

```
root@blockscoutdigitalocean:~# systemctl status blockscout
● blockscout.service - Blockscout Web App
   Loaded: loaded (/etc/systemd/system/blockscout.service; disabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Mon 2019-06-03 13:04:36 UTC; 1min 12s ago
  Process: 25967 ExecStart=/usr/local/bin/mix phx.server (code=exited, status=200/CHDIR)
 Main PID: 25967 (code=exited, status=200/CHDIR)

Jun 03 13:04:36 blockscoutdigitalocean systemd[1]: blockscout.service: Main process exited, code=exited, status=200/CHDI
Jun 03 13:04:36 blockscoutdigitalocean systemd[1]: blockscout.service: Failed with result 'exit-code'.
Jun 03 13:04:36 blockscoutdigitalocean systemd[1]: blockscout.service: Service hold-off time over, scheduling restart.
Jun 03 13:04:36 blockscoutdigitalocean systemd[1]: blockscout.service: Scheduled restart job, restart counter is at 5.
Jun 03 13:04:36 blockscoutdigitalocean systemd[1]: Stopped Blockscout Web App.
Jun 03 13:04:36 blockscoutdigitalocean systemd[1]: blockscout.service: Start request repeated too quickly.
Jun 03 13:04:36 blockscoutdigitalocean systemd[1]: blockscout.service: Failed with result 'exit-code'.
Jun 03 13:04:36 blockscoutdigitalocean systemd[1]: Failed to start Blockscout Web App.
```

**Comment by ali92hm** [comment]
So usually the VM images used by different cloud providers can have different software installed by default. This is probably the case in this situation, although you are using Ubuntu 16.04 LTS DigitalOcean probably has different base software on their image than Azure.

This script was tested on the Azure Ubuntu VM, so it is possible that it wont work on other environments. You can always follow the [BlockScout](https://github.com/poanetwork/blockscout) install instructions and set it up on your desired environment.

**Comment by Chrissie** [comment]
@ali92hm Sorry to say, I think you did not read my previous comments already in which I stated I already have tried the solutions in Azure, also after your 'solution'.

Can you please help me and try to setup the connection  to my specific blockchain, I can email you the endpoints if you want. Thanks.

**Comment by ali92hm** [comment]
Sorry about that. Sure, I send you an email.

**Comment by Chrissie** [comment]
Well. It turns out, when you get a 502 error you have set one of the endpoints wrong. The current documentation and install script is working.

@ali92hm Many thanks for proving the man behind the computer (me) is the problem, not the computer itself.

**Comment by danielnorkin** [comment]
Where did you find the rpc endpoint that worked for you? I've been
following this also

**Comment by ali92hm** [comment]
Hey @danielnorkin,

The POA deployment provisions a couple of VM and a load balancer. The IP address associated with the load balancer is the rpc endpoint to the network (on port 8540).

For websocket, you can pick the IP address of one of the VMs and use it as the ws endpoint (port 8547)


RPC: `http://<load balancer ip>:8540`
Websocket: `ws://<public ip of one of the blockchain vms>:8547`

**Comment by danielnorkin** [comment]
Thanks for writing back. I have been able to deploy blockscout, however the
blocks aren't updating
