### ISSUE TITLE
Feature request: Update Blockscout to include contract verification

### ISSUE THREAD

**Issue by Chrissie** [Azure-Samples/blockchain#184]
Feature Request: Update the Blockscout version.

I would like to verify Smart Contracts on source code. This is already an implemented feature in Blockscout, [read the docs](https://blockscout.com/poa/core/api_docs#verify).

This feature is not available in the blockscout version that installs from the current install script on master. Editing the script to a new blockscout version gives me the problems described in #182 .

**Comment by ramyapradhan** [comment]
Hello @Chrissie, thank you for your valuable suggestion.  We have added this to our backlog and will therefore be closing this issue.  

Thank you!
