### ISSUE TITLE
issue  azureBlockchainWorkbenchUpgradeTov1_7_0.ps1 Get-AzServiceBusQueue

### ISSUE THREAD

**Issue by jagilber** [Azure-Samples/blockchain#185]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [x ] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
> script azureBlockchainWorkbenchUpgradeTov1_7_0.ps1 fails 100% for me
$serviceBusNs is object but Get-Az(ureRm)ServiceBusQueue -Namespace expects string

### Any log messages given by the failure
>
```
Get-AzServiceBusQueue : 'namespaceName' exceeds maximum length of '50'.
At line:17 char:10
+ $queue = Get-AzServiceBusQueue -ResourceGroupName $ResourceGroupName  ...
+          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [Get-AzServiceBusQueue], ValidationException
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.ServiceBus.Commands.Queue.GetAzureRmServiceBusQueue
```
and
```
Cannot convert 'System.Object[]' to the type 'System.String' required by parameter 'Namespace'. Specified method is not supported.
At /home/kian_genteman/azureBlockchainWorkbenchUpgradeTov1_7_0.ps1:333 char:81
+ ... ResourceGroupName $ResourceGroupName -Namespace $serviceBusNs -Name $ ...
+                                                     ~~~~~~~~~~~~~
+ CategoryInfo          : InvalidArgument: (:) [Get-AzServiceBusQueue], ParameterBindingException
+ FullyQualifiedErrorId : CannotConvertArgument,Microsoft.Azure.Commands.ServiceBus.Commands.Queue.GetAzureRmServiceBusQueue
New-AzServiceBusQueue : Cannot convert 'System.Object[]' to the type 'System.String' required by parameter 'Namespace'. Specified method is not supported.

```
### Expected/desired behavior
> $serviceBusNs.Name should be used for Get-Az(ureRm)ServiceBusQueue -Namespace

### OS and Version?
> Windows 10

### Versions
> any

### Mention any other details that might be useful
submitting PR.

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by ramyapradhan** [comment]
Hello @jagilber, I am closing this issue because of your fixes.  Please let us know if there is anything more that we can help you with.
Thank you!
