### ISSUE TITLE
workbench upgrade script failure on VMSS custom script extension with exit code 2

### ISSUE THREAD

**Issue by zhenfengta** [Azure-Samples/blockchain#188]
> Please provide us with the following information:
> ---------------------------------------------------------------
I was using the Azure Cloud Shell. The two commands I used (the second one is the one that caused the error) are below:

PS Azure:\\> cd; Invoke-WebRequest -Uri https://aka.ms/workbenchUpgradeScript -OutFile azureBlockchainWorkbenchUpgradeTov1_7_0.ps1

and run the upgrade script.

We got error
Error: 

Update-AzVmss : Long running operation failed with status 'Failed'. Additional Info:'VM has reported a failure when processing extension 'Initialize-Machine'. Error message
: 'Enable failed: failed to execute command: command terminated with exit status=2
[stdout]
Response status code for eth_blockNumber request is 000
The RPC endpoint is inaccessible.
[stderr]
curl: (28) Connection timed out after 5001 milliseconds
'.'
ErrorCode: VMExtensionProvisioningError
ErrorMessage: VM has reported a failure when processing extension 'Initialize-Machine'. Error message: 'Enable failed: failed to execute command: command terminated with ex
it status=2
[stdout]
Response status code for eth_blockNumber request is 000
The RPC endpoint is inaccessible.
[stderr]
curl: (28) Connection timed out after 5001 milliseconds
'.
ErrorTarget:
StartTime: 6/18/19 3:55:14 PM
EndTime: 6/18/19 3:55:15 PM
OperationID: 714589c9-7e06-440a-9556-ae8f4fdcbb67
Status: Failed

+ ... orkerVMSS = Update-AzVmss -ResourceGroupName $ResourceGroupName -VMSc ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : CloseError: (:) [Update-AzVmss], ComputeCloudException
+ FullyQualifiedErrorId : Microsoft.Azure.Commands.Compute.Automation.UpdateAzureRmVmss

Unable to update the Workbench Worker VM. Please wait several minutes and try to run this script again. A description of the error can be found above.
At /home/user/workbenchUpgradeScriptV2.ps1:449 char:5
+     throw 'Unable to update the Workbench Worker VM. Please wait seve ...
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : OperationStopped: (Unable to update th\\u2026can be found above.:String) [], RuntimeException
+ FullyQualifiedErrorId : Unable to update the Workbench Worker VM. Please wait several minutes and try to run this script again. A description of the error can be found above.

the failure is at Update-AzVmss, which is a simple alias for Update-AzureRmVmss PS cmdlet 
# This cmdlet will perform an update on the VMSS if required, or just return if the goal configuration is the same as the current configuration
$workerVMSS = Update-AzVmss -ResourceGroupName $ResourceGroupName -VMScaleSetName $workerVMSS.Name -VirtualMachineScaleSet $workerVMSS
if(-Not $workerVMSS)
{
    throw "Unable to update the Workbench Worker VM. Please wait several minutes and try to run this script again. A description of the error can be found above."
}

What this line of code did is:
Download the shell script from https://catalogartifact.azureedge.net/publicartifacts/microsoft-azure-blockchain.azure-blockchain-workbench-c635569f-6278-46aa-bf98-f978026b1103-azure-blockchain-workbench/Artifacts/scripts/runScripts.sh and run that customer script in your VMSS. 
And above script seems to fail in this line:
check_endpoint() { status_code=$(curl $CURLARGS -X POST $1 --data '{"jsonrpc":"2.0","method":"eth_blockNumber","params":[],"id":1}' -H "Content-Type:application/json" --write-out %{http_code} --output /dev/null)

### This issue is for a: (mark with an `x`)
```
- [X ] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
>

### Any log messages given by the failure
>

### Expected/desired behavior
>

### OS and Version?
> Windows 7, 8 or 10. Linux (which distribution). macOS (Yosemite? El Capitan? Sierra?)

### Versions
>

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by ramyapradhan** [comment]
Hello @zhenfengta, 

Thank you for your message.  Azure Blockchain Workbench from version 1.7.0 onwards supports bringing your own RPC endpoint if you do not wish to use the default Quorum endpoint deployed with 1.7.0.  This endpoint of yours should be an Ethereum PoA endpoint.  

This particular message could mean an issue with any of the Azure resources that Workbench relies upon.  This issue usually goes away on retry after some time.

I'd recommend retrying.  Please let us know if you are still running into this issue.

Thanks!

**Comment by ramyapradhan** [comment]
Hello @zhenfengta,

I am writing to inform you that I will be closing this issue since it has been open for over 30 days.  Please feel free to re-open this if required.

Thanks,
Ramya

**Comment by filzatariq** [comment]
@ramyapradhan  I am also facing the same error with adding my existing RPC endpoint of ethereum POA. My Azure Blockchain workbench deployment is getting failed. Kindly help
