### ISSUE TITLE
From where this msg come from? Is it a typo?

### ISSUE THREAD

**Issue by foyzulkarim** [Azure-Samples/blockchain#189]
https://github.com/Azure-Samples/blockchain/blob/a08558a0d48e6a45857ae4a72dfabdb9889edd1c/blockchain-workbench/application-and-smart-contract-samples/hello-blockchain/HelloBlockchain.sol#L19

In the above line we are accessing `msg` variable, but in the constructor we are getting `message` variable. Is there any typo? From where this `msg` variable come from?

**Comment by ali92hm** [comment]
`msg` is one the special variables in solidity. You can read more about it [here](https://solidity.readthedocs.io/en/v0.4.24/units-and-global-variables.html#block-and-transaction-properties)
