### ISSUE TITLE
Unable to add myself to workbench applications

### ISSUE THREAD

**Issue by baishali-ghosh** [Azure-Samples/blockchain#19]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
- [x] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
> 

* I deployed workbench to my Azure account linked with my corporate Microsoft account: xyz@microsoft.com
* The workbench got deployed. I am added to the AD app which is linked to the workbench.
* When I navigate to the UI, I am able to deploy new blockchain applications. [See screenshot]
![image](https://user-images.githubusercontent.com/3686662/42408918-08d9e874-81f0-11e8-94e2-74eadb26c98c.png)
*  But I am not able to perform any operations on the deployed apps because I cannot add myself to them. 

### Any log messages given by the failure
> 
![image](https://user-images.githubusercontent.com/3686662/42408929-33c1df6a-81f0-11e8-9a89-7f1160ad3ebc.png)
Error 403: Authorization_RequestDenied - Insufficient privileges to complete the operation.
 I am able to deploy new apps but not perform operations on them.

### Expected/desired behavior
> I should be able to perform operations on deployed apps. I am an administrator on the AD API app.

**Comment by brendalee** [comment]
Make sure you have added the appropriate permissions in the AAD prerequisite setup steps. You need to grant the Graph API certain permissions.

**Comment by brendalee** [comment]
https://docs.microsoft.com/en-us/azure/blockchain-workbench/blockchain-workbench-deploy#add-graph-api-required-permissions
