### ISSUE TITLE
Authentication using IConfidentialClientApplicationBuilder rather than AuthenticationContext

### ISSUE THREAD

**Issue by Meberem** [Azure-Samples/blockchain#191]
What is the correct way of using `IConfidentialClientApplicationBuilder` to get a Service Principal token in dotnet core? I can see the [example which uses an AuthenticationContext](https://github.com/Azure-Samples/blockchain/blob/master/blockchain-workbench/auth-samples/netcore/Program.cs) but I was hoping to use the builder. 

### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
- [x] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
> N/a

### Any log messages given by the failure
> N/a

### Expected/desired behavior
> N/a

### OS and Version?
> Windows 7, 8 or 10. Linux (which distribution). macOS (Yosemite? El Capitan? Sierra?)

### Versions
> N/a

### Mention any other details that might be useful
N/a

**Comment by ramyapradhan** [comment]
Hello @Meberem, can you please provide more details on your particular use case, thanks!

**Comment by Meberem** [comment]
Honestly, I can't remember the details now. I was creating a webapp that had some similar features to the default explorer one provided by Microsoft, I had many issues logging into the app and staying authenticated, i.e. my authentication approach only returned v2 tokens and the api required v1 tokens. I think that was the crux of the issue, and I thought looking at the documentation using IConfidentialClientApplicationBuilder would let me configure it in such a way to accomplish my goals. It was a while ago and I can't quite remember all the details, sorry.

**Comment by ramyapradhan** [comment]
I see, there have been quite a few changes since this thread was created.  I think for now, @Meberem , I will close this issue, but if you run into it again, please feel free to re-open this issue.
Thanks,
Ramya
