### ISSUE TITLE
Invalid Syntax

### ISSUE THREAD

**Issue by nishantwrp** [Azure-Samples/blockchain#199]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
>  run anything with swagger_client

### Any log messages given by the failure
> File "/home/nishantwrp/Desktop/Web/Projects/Codefundo-2k19/venv/lib/python3.7/site-packages/swagger_client-1.0.0-py3.7.egg/swagger_client/api/applications_api.py", line 121
    async=params.get('async'),

### Expected/desired behavior
>

### OS and Version?
> Windows 7, 8 or 10. Linux (which distribution). macOS (Yosemite? El Capitan? Sierra?)
Ubuntu 19

### Versions
>

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by ramyapradhan** [comment]
Hello @nishantwrp,

I am writing to request more details on this issue.  If you are still having this issue, can you please elaborate more on what your use case is and your expected behavior?

Thanks,
Ramya

**Comment by ramyapradhan** [comment]
Hi @nishantwrp, please feel free to re-open this issue if you are still facing this issue.

Thanks,
Ramya
