### ISSUE TITLE
Script Link is broken

### ISSUE THREAD

**Issue by jaypetrin** [Azure-Samples/blockchain#2]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
- [X] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
>Click on the script link in the readme.md for Azure Blockchain Workbench Pre-Deployment Script

### Any log messages given by the failure
>404 returned

### Expected/desired behavior
>script file download

### OS and Version?
> NA

### Versions
>

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by mmercuri** [comment]
Thanks for that. This has been updated.
