### ISSUE TITLE
cloudShellPreDeploy.ps1: Need to connect to the correct AAD tenant before provisioning resources

### ISSUE THREAD

**Issue by SenthuranSivananthan** [Azure-Samples/blockchain#20]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for:
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
1. Create new AAD tenant
2. Launch Cloud Shell and login to the corporate tenant (i.e. microsoft.onmicrosoft.com)
3. Execute cloudShellPreDeploy.ps1 and enter the tenant name that was created in step 1.

### Any log messages given by the failure
> Standard outputs

### Expected/desired behavior
>  Admin user and app registration are created in the new AAD tenant

### Actual behavior
> Admin user and app registration are created in the tenant that was used to login to Cloud Shell.

### Workaround

Before executing cloudShellPreDeploy.ps1, execute 

```powershell
Connect-AzureAD -TenantId <AAD_GUID>
```

### OS and Version?
> Not applicable

### Versions
> Not applicable

**Comment by mmercuri** [comment]
We can change this in the doc, thanks for the feedback.
