### ISSUE TITLE
Inaccurate documentation on logic apps

### ISSUE THREAD

**Issue by manikyabard** [Azure-Samples/blockchain#201]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
- [x ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
> Incorrect Documentation
https://github.com/Azure-Samples/blockchain/blob/master/blockchain-workbench/messaging-integration-samples/ExecuteLogicBasedOnPropertyValueAfterASpecificContractAction.md

Follow this link, create logic app, connect blockchain workbench, then follow the steps in the doc.

### Any log messages given by the failure
> None

### Expected/desired behavior
> After a function is invoked in blockchain workbench, an action takes place as specified in logic apps.

### OS and Version?
> Every OS because of inaccurate documentation

### Versions
> 

### Mention any other details that might be useful
In the logic apps after connecting to your blockchain workbench, the documentation on
(https://github.com/Azure-Samples/blockchain/blob/master/blockchain-workbench/messaging-integration-samples/ExecuteLogicBasedOnPropertyValueAfterASpecificContractAction.md)
has inaccurate steps.
> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by ramyapradhan** [comment]
Hello @manikyabard,

Thank you for making the changes!  I am writing to inform you that I will be closing this issue since you have graciously taken the time to fix it.

Thank you,
Ramya
