### ISSUE TITLE
Coud not add admin user for ABW application

### ISSUE THREAD

**Issue by ygizhitsa** [Azure-Samples/blockchain#204]
Step to reproduce:

- Have created ABW[ application](https://azdobc-j7sksw.azurewebsites.net/applications)
- Trying to upload smart contract and have realized that I'm not Admin user
- Found registered application in order to assign myself to Admin group - admin group is disabled   
![image](https://user-images.githubusercontent.com/16059989/66224071-0afe3380-e6a3-11e9-9ccb-d07a50cd4e11.png))
 
Additional info
- This is my MSDN subscription 
-  Manifest has Administrator group reference

**Comment by ramyapradhan** [comment]
Hello @ygizhitsa, one quick work around for this is to try and run the upgrade script that will automatically assign the admin role to you.  Please let us know if that does not fix this issue for you.
Thanks!

**Comment by ramyapradhan** [comment]
Hello @ygizhitsa,

I am writing to inform you that I will be closing this issue since it has been open for more than 30 days.  Please feel free to re-open it if required.

Thanks,

Ramya
