### ISSUE TITLE
Got bad request when trying to create a new contract via api call

### ISSUE THREAD

**Issue by zzq9624** [Azure-Samples/blockchain#207]
Following the instructions, I can successfully get contracts by calling API **https://{xxx}-api.azurewebsites.net/api/v2/contracts?workflowId=1&sortBy=Timestamp&top=50&skip=0**, but I fail to create a new contract by calling API **https://{xxx}-api.azurewebsites.net/api/v2/contracts?workflowId=1&contractCodeId=1&connectionId=1**, I got 400 error code with the same access token.

Anyone could help? Thanks in advance.

**Comment by codyborn** [comment]
Hi @zzq9624,

Can you confirm that you've specified the workflowActionInput in the body of the request? I recommend making the create contract request in the browser Workbench UI and referencing the network trace to make sure you have all of the required parameters in the correct format.

Regards,
Cody

**Comment by zzq9624** [comment]
@codyborn 
Yes, I did so and compared the request body captured in network trace with the version I used in source code, they are the same. See the request body I used as below.
{"workflowFunctionId":1,"workflowActionParameters":[{"name":"message","value":"justtess"}]}

I tried replace the access token with the one I captured via fiddler (manually create a contract instance on web UI-https://{xxx}-api.azurewebsites.net), I could successfully post the request.

**Comment by codyborn** [comment]
> I could successfully post the request.
Does this mean you've got it working? Was the problem with an expired token?

**Comment by zzq9624** [comment]
@codyborn
It still does not work. I am pretty sure the token is not expired, requesting token and sending request are in the same API. 

I could successfully get contacts but failed to post a new contract:

I can successfully get contracts by calling API https://{xxx}-api.azurewebsites.net/api/v2/contracts?workflowId=1&sortBy=Timestamp&top=50&skip=0, but I fail to create a new contract by calling API https://{xxx}-api.azurewebsites.net/api/v2/contracts?workflowId=1&contractCodeId=1&connectionId=1, I got 400 error code with the same access token

**Comment by codyborn** [comment]
Hi @zzq9624 ,

I've gone through the steps using a new Workbench instance and submitting the requests directly using Postman.  I was able to get a 200 on the request and had the contract created successfully.
I copied the URL, bearer token, and body from the dev console in the browser.  I set the bearer token in Postman and set the Content-Type header to be "application/json". Please double check your URL, auth header, content type, and the request body and let me know if you're still hitting the 400.

Thanks,
Cody

**Comment by ramyapradhan** [comment]
Hello @zzq9624, 

I am writing to check in with you to ensure that you are unblocked.  Please feel free to reach out if you need any help with this issue.

Thanks!

**Comment by ramyapradhan** [comment]
Hello @zzq9624,

I am writing to inform you that I will be closing this issue since it has been over 30 days since we last heard from you.  Please feel free to re-open this if required.

Thanks,
Ramya
