### ISSUE TITLE
Create App using REST API

### ISSUE THREAD

**Issue by ygizhitsa** [Azure-Samples/blockchain#210]
### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ x] feature request
- [ x] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
> In the App Portal creating an application is a 2 steps process
- Upload json file - roles and workflow
- Upload sol  - smart contract

Trying to reproduce the same behavior using ABW Rest API is confusing:
Swagger definition for the POST API/Application specifies only json file. Microsoft documentation for this POST method is completely useless 

![image](https://user-images.githubusercontent.com/16059989/68030430-d5dc0580-fc8f-11e9-9aa8-a252ab22239b.png)

Questions:
- Is there a document that describes right  sequence of events
- Is there an example that does it ( PowerShell and C# preferable)
- Is there are Portal Application and/or REST Service  source code available

**Comment by ramyapradhan** [comment]
Hello @ygizhitsa,

I am sorry for the inconvenience that the lack of clarity in the documentation regarding this has caused you. I have created a backlog item to add a fix. 

Here is how to create an application using just the REST API calls:

1. Upload the application's JSON file using the Application POST method (the one you have shown here -- /api/v1/applications).  One the upload is successful, you will get an application ID.  

2.  Use this application ID and ledger ID (Ethereum ledger ID value is 1 and that is the only one supported now) and do a POST on  /api/v1/applications/{applicationID}/contractCode.  Here the contract file can either be a .sol file or a .zip file.

Here is how you can do it in C#:

Posting the application's JSON file:
`
/* 
    apiRequester = instance of your API Client
    appFilePath = Complete path to your application's JSON file
    User.Admin = a valid admin user id (check your user and role assignment database for this ID value)
*/
apiRequester.Post("/api/v1/applications", Helpers.GetFileInputObject("appFile", appFilePath, out FileStream configFs), out createdApplicationId, out retStatus, User.Admin);
`
The output of this call is createdApplicationId.

Posting the application's contract code:
`
/*
  apiRequester = instance of your API Client 
  createdApplicationId = application ID from the first POST call
   ETHEREUM_LEDGER_ID = 1 (or check your database's Ledger table for the correct ID)
   ledgerFilePath = Complete path to your application's contract code file (either .sol or .zip)
   User.Admin = a valid admin user id (check your user and role assignment database for this ID value)
*/
apiRequester.Post($"/api/v1/applications/{createdApplicationId}/contractCode?ledgerId={ETHEREUM_LEDGER_ID}", Helpers.GetFileInputObject("contractFile", ledgerFilePath, out FileStream impFs), out int ledgerImplId, out retStatus, User.Admin);
`
The output of this call is the ledgerImplId that indicates the id of this contract code on the ledger.  This is just an informational piece and is not used in any of the REST API calls.

Please let me know if any other clarifications are needed.

Thanks,
Ramya

**Comment by ramyapradhan** [comment]
Hello @ygizhitsa , I am writing to let you know that I will be closing this issue since it has been over a month since a solution was suggested.  I hope this will be ok with you.  If at any point, you require more clarifications, please feel free to re-open this issue and we will be more than happy to assist you.

Thanks,
Ramya
