### ISSUE TITLE
Logic App Connector - No support for uint256[] and string[] in ABI

### ISSUE THREAD

**Issue by mjtpena** [Azure-Samples/blockchain#218]
### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [x] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
> Use the Ethereum Connector, and under the abi put in a parameter with uint256[] data type such as below:

"abi": "[\n{\n    \"constant\": false,\n    \"inputs\": [\n      { \"internalType\": \"address\", \"name\": \"to\", \"type\": \"address\" },\n      { \"internalType\": \"uint256[]\", \"name\": \"tokenIds\", \"type\": \"uint256[]\" },\n      { \"internalType\": \"uint256[]\", \"name\": \"amounts\", \"type\": \"uint256[]\" },\n      { \"internalType\": \"string[]\", \"name\": \"metaDataList\", \"type\": \"string[]\" }\n    ],\n    \"name\": \"batchMintUniqueTokenTo\",\n    \"outputs\": [],\n    \"payable\": false,\n    \"stateMutability\": \"nonpayable\",\n    \"type\": \"function\"\n  }\n]",

### Any log messages given by the failure
> Error executing the api '/contractSchema/functions/batchMintUniqueTokenTo/metadata'
{
  "status": 400,
  "message": "The datatype 'uint256[]' is not supported\r\nclientRequestId: d3e4a0c7-0906-4ac6-9ea2-1acb2b5e8d0b",
  "source": "blockchainethereum-ae.azconn-ae.p.azurewebsites.net"
}

### Expected/desired behavior
> Can pass in an array as an input parameter / argument

### OS and Version?
> Windows 10

**Comment by imnaseer** [comment]
This is a known limitation of the existing version of the connector and support for the feature will be considered in future versions.
