### ISSUE TITLE
collectBlockchainWorkbenchTroubleshooting.ps1 problem

### ISSUE THREAD

**Issue by ygizhitsa** [Azure-Samples/blockchain#22]
### Minimal steps to reproduce
run collectBlockchainWorkbenchTroubleshooting.ps1 
get PowerShell module version exception
followed an instruction and have installed  AzureRM module locally  and in Cloud Shell

### Any log messages given by the failure
PS C:\Projects\blockchain\blockchain-workbench\scripts\troubleshooting> .\collectBlockchainWorkbenchTroubleshooting.ps1 -SubscriptionID "a69dce......e3be1" -ResourceGroupName "BaaS-RG"
The required version of the Azure Powershell cmdlets was not detected. We recommend that you follow the
    instructions on https://www.powershellgallery.com/packages/AzureRM/6.0.1 to update to a compatible version. Or,
    you can run  this script using Azure Cloud shell at https://shell.azure.com/powershell
At C:\Projects\blockchain\blockchain-workbench\scripts\troubleshooting\collectBlockchainWorkbenchTroubleshooting.ps1:438 char:5
+     throw "The required version of the Azure Powershell cmdlets was n ...
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (The required ve....com/powershell:String) [], RuntimeException
    + FullyQualifiedErrorId : The required version of the Azure Powershell cmdlets was not detected. We recommend that you follow the
    instructions on https://www.powershellgallery.com/packages/AzureRM/6.0.1 to update to a compatible version. Or,
    you can run  this script using Azure Cloud shell at https://shell.azure.com/powershell

### Expected/desired behavior
>  collect ABW troubleshooting info

### OS and Version?
> Windows 7, 8 or 10. Linux (which distribution). macOS (Yosemite? El Capitan? Sierra?)
Windows 10 and Cloud Shell (Edge)
### Versions
>

**Comment by brendalee** [comment]
Looks like your powershell may need to be updated. Update your powershell version and this should be fixed.
