### ISSUE TITLE
Error "There was a problem with login. Please try again." on "Azure AD configuration script" for Azure Blockchain Workbench

### ISSUE THREAD

**Issue by karlitoz007** [Azure-Samples/blockchain#222]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [X] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
> Deploy a new "Azure Blockchain Workbench" service following [the official guide from Microsoft Docs](https://docs.microsoft.com/en-us/azure/blockchain/workbench/deploy#deploy-blockchain-workbench) (as recommended, choose "Add Later" on "Azure Active Directory settings")
> Open the URL related to the "Azure Blockchain Workbench" deployed ([follow this official guide](https://docs.microsoft.com/en-us/azure/blockchain/workbench/deploy#blockchain-workbench-web-url))
> The URL will show a "Welcome to Azure Blockchain Workbench" message with instructions to set-up AAD.
> Follow the "Step 1. Launch Cloud Shell and run the following command" listed on the previous URL following [the official guide](https://docs.microsoft.com/en-us/azure/blockchain/workbench/deploy#azure-ad-configuration-script). It includes an script to be executed on Azure Cloud Shell with PowerShell (IDs masked with ***): 
`cd; Invoke-WebRequest -Uri https://aka.ms/workbenchAADSetupScript -OutFile workbenchAADSetupScript.ps1; ./workbenchAADSetupScript.ps1 -SubscriptionID *** -ResourceGroupName *** -DeploymentId ***`
> **Executing that PS script will fail (see next section for error message)**

### Any log messages given by the failure
> ERROR: There was a problem with login. Please try again.
> ERROR MESSAGE: The expression after '&' in a pipeline element produced an object that was not valid. It must result in a command name, a script block, or a CommandInfo object.

### Expected/desired behavior
> You should be prompted to authenticate to the Azure AD tenant using a browser. Open the web URL in a browser, enter the code, and authenticate (as described on [the official guide here](https://docs.microsoft.com/en-us/azure/blockchain/workbench/deploy#azure-ad-configuration-script))

### OS and Version?
> Windows 10, but all steps are online via web browser.

### Versions
> Current version as of 12 february 2020 (1.8.0)

### Mention any other details that might be useful
> Looks like [the PS script](https://github.com/Azure-Samples/blockchain/blob/master/blockchain-workbench/scripts/aad-setup/workbenchAADSetup.ps1) was updated more than 1 year ago, so maybe was working before but not anymore.

**Comment by sivataras** [comment]
I am facing the same issue

**Comment by theMobiusStrip** [comment]
Thanks for feedback! We are working on the issue

**Comment by theMobiusStrip** [comment]
There was some recent changes to Azure Cloud Shell. While we are working on a solution, here is some workaround:

Before running `cd; Invoke-WebRequest -Uri https://aka.ms/workbenchAADSetupScript -OutFile workbenchAADSetupScript.ps1; ./workbenchAADSetupScript.ps1 -SubscriptionID *** -ResourceGroupName *** -DeploymentId ***`

Run `Remove-Item -Path Function:\Connect-AzureAD` in your Azure Cloud Shell session

**Comment by ramyapradhan** [comment]
Hello @karlitoz007 and @sivataras, the fix has been rolled out.  Please try it and in case if that does not work, please feel free to re-open this issue.
Thanks,
Ramya
