### ISSUE TITLE
 Unable to map users in Azure Blockchain workbench for a particular contract.

### ISSUE THREAD

**Issue by anjalisn4** [Azure-Samples/blockchain#226]
Hi Team

We are unable to add a user to a contract through Azure Workbench UI. On trying to add, the UI fails to fetch the releavnt user from Azure AD and logs out. This behavior is noticed in a loop. Request to kindly look into this.

Note: As a work around we are able to add users using Azure Workbench swagger API.

https://social.msdn.microsoft.com/Forums/en-US/179a23f0-0d72-41df-87ef-de58e40edaad/unable-to-map-users-in-azure-blockchain-workbench-for-a-particular-contract?forum=azureblockchain

**Comment by PatAltimore** [comment]
Hi @anjalisn4,

I remember seeing this behavior before. Verify you are allowing ID Tokens in the Reply URL configuration. https://docs.microsoft.com/en-us/azure/blockchain/workbench/deploy#configuring-the-reply-url 

Pat

**Comment by anjalisn4** [comment]
Hi Pat,

Apologies for the delay in response. The reply URL is configured as provided in the link along with the the Advanced setting. however the issue is still seen.

**Comment by PatAltimore** [comment]
Hi @anjalisn4,

Good to hear it's working. 👍

Pat
