### ISSUE TITLE
Delivering Data from IoT Hub to Azure Blockchain Workbench

### ISSUE THREAD

**Issue by altfo** [Azure-Samples/blockchain#23]
The instruction in the https://github.com/Azure-Samples/blockchain/blob/master/blockchain-workbench/iot-integration-samples/ConfigureIoTDemo.md is not very clear

I am getting error when I execute the Update User Query need to be [User] with brackets
The Hub EndPoint Query I am not sure what to add? temperature query?

**Comment by mmercuri** [comment]
Page updated, put User in brackets.

Yes for the query you can specify if you'd like to filter on just certain temperature ranges or send everything through.
