### ISSUE TITLE
What will happen after Azure Blockchain will be retired?

### ISSUE THREAD

**Issue by OscarCanek** [Azure-Samples/blockchain#247]
Is this project still gonna work after this happens?

<img width="899" alt="image" src="https://user-images.githubusercontent.com/3521524/120564430-1fd72100-c3c8-11eb-86f1-4450693f67a1.png">

**Comment by caleteeter** [comment]
@OscarCanek after September 10, there are alternatives that these existing projects can use.  Specifically, Azure Blockchain Workbench can target other endpoints, such as the upcoming [QBS](https://consensys.net/QBS) offering from ConsenSys.  Additionally, creating a simple network with the [Quorum Dev Quickstart](https://azuremarketplace.microsoft.com/en-us/marketplace/apps/consensys.quorum-dev-quickstart?tab=Overview) and targetting this from workbench or these samples will work as well.  

We are currently working on automation of the [Qubernetes ](https://docs.goquorum.consensys.net/en/stable/Concepts/Qubernetes/Qubernetes-Overview/#:~:text=Qubernetes%20Qubernetes%20is%20a%20project%20for%20generating%20GoQuorum,Qubernetes%20is%20customizable%20for%20more%20advanced%20Kubernetes%20deployments.) for Azure as a solution as well.

Lastly, new versions of the logic app connectors will be released to remove the ABS specific integration, however they will work with other Ethereum based chains.
