### ISSUE TITLE
No able to create contract using this .sol project

### ISSUE THREAD

**Issue by jigarrdesai** [Azure-Samples/blockchain#27]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
>

### Any log messages given by the failure
>

### Expected/desired behavior
>

### OS and Version?
> Windows 7, 8 or 10. Linux (which distribution). macOS (Yosemite? El Capitan? Sierra?)

### Versions
>

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by brendalee** [comment]
What's the errors you are seeing?

**Comment by mmercuri** [comment]
No response, closing the issue. Will re-open if the issue persists.
