### ISSUE TITLE
Link to download SQL Stored Procedure is missing in blockchain/blockchain-workbench/iot-integration-samples/ConfigureIoTDemo.md page

### ISSUE THREAD

**Issue by gowthamreddyvintha** [Azure-Samples/blockchain#36]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
>

### Any log messages given by the failure
>

### Expected/desired behavior
>

### OS and Version?
> Windows 7, 8 or 10. Linux (which distribution). macOS (Yosemite? El Capitan? Sierra?)

### Versions
>

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by davidglassborow** [comment]
https://github.com/Azure-Samples/blockchain/blob/master/blockchain-workbench/iot-integration-samples/SQL/IoTSprocs.sql

**Comment by mmercuri** [comment]
Link added to document.
