### ISSUE TITLE
Could not find BlockChian WorkBench Application error log 

### ISSUE THREAD

**Issue by gowthamreddyvintha** [Azure-Samples/blockchain#37]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
>
I am working on a RegisteredTemperature application on the workbench. When a new contract is created it is giving me an error 
**It looks like something went wrong with creating contract 7. Contact your administrator for help resolving the problem.**
Where to find the error logs on BLock Chain Workbench
### Any log messages given by the failure
>
### Expected/desired behavior
>

### OS and Version?
> Windows 7, 8 or 10. Linux (which distribution). macOS (Yosemite? El Capitan? Sierra?)

### Versions
>

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by mmercuri** [comment]
We provided robust error detail inside of Application Insights.

If you navigate to the resource group that you specified when deploying Azure Blockchain Workbench, you will find an Application Insights resource.

Click on this and select search and you will find robust telemetry.
