### ISSUE TITLE
Unable to deploy new applications to the BlockChain Workbench

### ISSUE THREAD

**Issue by gowthamreddyvintha** [Azure-Samples/blockchain#38]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
>1. login to BlockChain Workbench app 
   2. +New upload .json, .sol files and click on Deploy
   

### Any log messages given by the failure
>

### Expected/desired behavior
Deploy the new application and display on WorkBench 
### OS and Version?
> Windows 7, 8 or 10. Linux (which distribution). macOS (Yosemite? El Capitan? Sierra?)

### Versions
>

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by mmercuri** [comment]
unable to reproduce
