### ISSUE TITLE
I can't retrieve parameters value passed from Logic APP to the activityhub 

### ISSUE THREAD

**Issue by myszon01** [Azure-Samples/blockchain#39]
Hi everyone,

I have an issue with calling smart contract function from logic app.

I am sending a massage to the activityhub from logic app to trigger a function on the contract. 

Logic app triggers this function corretly but my issue is that I can't see what parameters the Logic App passed to this function. When I trigger the same function from the  API endpoint I am able to see the parameters I passed to the function. Bellow is the message I am sending to the activityhub

{
    "ContractActionId": null,
    "ConnectionId": @{items('For_each')?['ConnectionId']},
    "UserChainIdentifier": "@{items('For_each')?['UserChainIdentifier']}",
    "ContractCodeArtifactBlobStorageURL": "@{items('For_each')?['ContractCodeBlobStorageUrl']}",
    "OperationName": "CreateContractAction",
    "ContractLedgerIdentifier": "@{items('For_each')?['ContractLedgerIdentifier']}",
    "WorkflowFunctionName": "@{items('For_each')?['WorkflowFunctionName']}",
    "WorkflowName": "@{items('For_each')?['WorkflowName']}",
    "ContractActionParameters": [
         {
            "name": "wifi",
            "value": "@{body('Parse_JSON')?['wifi']}"
        },
        {
            "name": "radio",
            "value": "@{body('Parse_JSON')?['radio']}"
        }
       
    ],
    "RequestId": "@{variables('RequestID')}"
}  

PS. I have looked in my SQL database and it looks like these parameters are not getting replicated from the blockchain to the dbo.ContractActionParameter table.  

Thanks,
Peter

**Comment by mmercuri** [comment]
Should be addressed in latest build.
