### ISSUE TITLE
Blockchain Workbench: Unable to add User to app

### ISSUE THREAD

**Issue by massilvaLaz** [Azure-Samples/blockchain#40]
Hi,

Created a new in Active Directory. Logging into my Blockchain Workbench site as Admin user. See my  New app icon.  Only 1 User (admin) listed. Click on App. Add Member. Do a search for members and no user found.
I checked the F12 console in my google chrome browser and I found this error:
" error:"Internal Server Error" "

I checked the graph API permissions and they are set properly but I can't add Members to the App.

**Comment by mmercuri** [comment]
User needs to be aded to the application. Upon navigating to the web page, an on chain identifier will be created for them.  Then when you go in as Admin, you can add them.
