### ISSUE TITLE
IoT Hub to Azure Blockchain (cannot Update User TABLE)

### ISSUE THREAD

**Issue by curtisho1** [Azure-Samples/blockchain#42]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [x ] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
https://github.com/Azure-Samples/blockchain/blob/master/blockchain-workbench/iot-integration-samples/ConfigureIoTDemo.md

I follow the document under the User Creation

Update "User" Set ExternalId = ‘<your device id here>’ where EmailAddress = ‘<insert email address here>’

The Script is successful executed but when I run select * from user. I cant see it is update in the User table. Also, 

the Iot can deliver to service bus but in the store procedure step, it will show below errors

![image](https://user-images.githubusercontent.com/39734762/45251121-71ffca80-b373-11e8-91bb-e0df3d7d87f0.png)

{
  "status": 400,
  "message": "Procedure or function 'GetContractInfoForDeviceId' expects parameter '@DeviceID', which was not supplied.\r\nclientRequestId: 6c5e7fa3-e5fe-45b2-8a85-2de22cf3ca16",
  "source": "sql-logic-cp-eastus.logic-ase-eastus.p.azurewebsites.net"
}

> 

### Any log messages given by the failure
>

### Expected/desired behavior
>

### OS and Version?
> Windows 7, 8 or 10. Linux (which distribution). macOS (Yosemite? El Capitan? Sierra?)

### Versions
>

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by curtisho1** [comment]
I put my Iot Device instead of using guid(). it works

![image](https://user-images.githubusercontent.com/39734762/45617004-9d856200-baa3-11e8-97c0-6ed395a1012c.png)

but in the next step, it said validation fails

![image](https://user-images.githubusercontent.com/39734762/45617057-bf7ee480-baa3-11e8-8af5-1fecccad33ca.png)

the message said Invalid type. 

    "message": "Invalid type. Expected Object but got Array.",

**Comment by mmercuri** [comment]
For the ExternalID, you should replace it with the ID used for the device - it could be the Mac Address, IoT Hub ID for the device, etc.

The issue you're seeing now is that you've got two users with the same ID and it's now returning an array.

Within the user table, set the external ID for one of the accounts to a different ID and you should be all set.
