### ISSUE TITLE
Error when running collectBlockchainWorkbenchTroubleshooting.ps1

### ISSUE THREAD

**Issue by Resultfactory** [Azure-Samples/blockchain#44]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
> run script .\collectBlockchainWorkbenchTroubleshooting.ps1 -Sub
scriptionID "<SubscriptionID>" -ResourceGroupName "ddblockchain"

### Any log messages given by the failure
>
`Invoke-WebRequest : {"error":{"message":"The request had some invalid properties","code":"BadArgumentError","innererror
":{"code":"SyntaxError","message":"Syntax Error"}}}
At C:\temp\blockchain\blockchain-workbench\scripts\troubleshooting\collectBlockchainWorkbenchTroubleshooting.ps1:240 ch
ar:17
+ ... $response = Invoke-WebRequest -UseBasicParsing -Uri $uri -Body $body  ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-WebRequest], WebExc
   eption
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeWebRequestCommand`
### Expected/desired behavior
>The ZIP file is not created because of the error

### OS and Version?
> Windows 10

### Versions
>

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by grcignav** [comment]
Hello, can you please confirm which version of PowerShell that you're using?

**Comment by sidkri** [comment]
In the command you ran, the SubscriptionId was specified as a blank string (i.e. "") which is causing the script to fail.

run script .\collectBlockchainWorkbenchTroubleshooting.ps1 -Sub
scriptionID "" -ResourceGroupName "ddblockchain"

Please re-open the issue if its still not working after specifying the SubscriptionId
