### ISSUE TITLE
Update URL for install_blockscout.sh in BlockScout setup guide

### ISSUE THREAD

**Issue by abcoathup** [Azure-Samples/blockchain#48]
### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
- [x] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
>
BlockScout setup (https://github.com/Azure-Samples/blockchain/blob/master/ledger/template/ethereum-on-azure/technology-samples/blockscout/README.md) has invalid URL to download install_blockscout.sh
Currently: http://www.github.com/azure-samples/blockchain/ledger/template/ethereum-on-azure/block-explorers/blockscout/install_blockscout.sh

Should be: https://raw.githubusercontent.com/Azure-Samples/blockchain/master/ledger/template/ethereum-on-azure/technology-samples/blockscout/install_blockscout.sh

**Comment by mmercuri** [comment]
Link updated.
