### ISSUE TITLE
Error in collectBlockchainWorkbenchTroubleshooting.ps1 line 471

### ISSUE THREAD

**Issue by jeffryvu** [Azure-Samples/blockchain#5]
https://github.com/Azure-Samples/blockchain/blob/f117d2efefdc148b81d09079d904020959942565/blockchain-workbench/scripts/troubleshooting/collectBlockchainWorkbenchTroubleshooting.ps1#L471

Line 471 says:
$apiWebsite = ($websites | Where-Object { $_.SiteName -like "*-api" })[0] # Select the Workbench API

However, the $websites doesn't contain a property SiteName. It does contain Name or RepositorySiteName, so any of these will work.

**Comment by mmercuri** [comment]
Jeffry - I've reached out to the dev for that script and will follow up.

**Comment by jeffryvu** [comment]
Issue has been fixed, so this can be closed.
