### ISSUE TITLE
FAILURE: Failed to create Azure AD application. Exiting...

### ISSUE THREAD

**Issue by EasonWang01** [Azure-Samples/blockchain#50]
<img width="1371" alt="screen shot 2018-10-15 at 7 27 01 pm" src="https://user-images.githubusercontent.com/11001914/46948365-69a45900-d0b0-11e8-9041-b23a86c58b9a.png">

Actual behavior: Not verbose information log for the fail result.

Expect behavior: Success create Azure AD application

**Comment by ali92hm** [comment]
Thanks for reporting this issue. Could you please double check that you have the permission to create a [AAD Application Registration ](https://docs.microsoft.com/en-us/azure/active-directory/develop/howto-create-service-principal-portal)through the Azure Portal in that directory?

We are in the process of rewriting that script to emit better error messages.

**Comment by EasonWang01** [comment]
Yes, able to create through the Azure Portal.
<img width="750" alt="2018-10-26 9 25 33" src="https://user-images.githubusercontent.com/11001914/47538876-188e3380-d900-11e8-9af9-e014494f536b.png">

**Comment by ali92hm** [comment]
I just updated the script to printout the exception. Could you please pull down the script again and rerun it? It should print out the problem

**Comment by EasonWang01** [comment]
```
Connect-AzureAD : Object reference not set to an instance of an object.
At /home/yicheng/workbenchAADSetup.ps1:72 char:16
+ $currentUser = Connect-AzureAD -TenantId $TenantName
+                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : AuthenticationError: (:) [Connect-AzureAD], AadAuthenticationFailedException
+ FullyQualifiedErrorId : Connect-AzureAD,Microsoft.Open.Azure.AD.CommonLibrary.ConnectAzureAD
```

But I can manually create an AD application then get the GUID and key.

**Comment by ali92hm** [comment]
I'm wondering if you're using a different account when you get prompted for logging in through powershell.

When you are prompted for navigating to 

> WARNING: To sign in, use a web browser to open the page https://microsoft.com/devicelogin and enter the code BB3SF9NJN to authenticate.

Could you open [https://microsoft.com/devicelogin](https://microsoft.com/devicelogin) in an incognito window and login with the same account you do as the portal?

**Comment by EasonWang01** [comment]
It will ask to pick an account after the code enter, and seems it's same account.

**Comment by ali92hm** [comment]
And you got the same error? There seems to be some problem with the login

**Comment by ali92hm** [comment]
@EasonWang01 I'm closing this issue, feel free to reopen it if your issue is not solved
