### ISSUE TITLE
It appears that Azure Cloudshell is not a compatible platform for the upgrade script

### ISSUE THREAD

**Issue by ahakala** [Azure-Samples/blockchain#53]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [ x ] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
1. Launch Azure Cloud Shell
2. copy upgrade script into user home
3. Install required modules
4. Run Scirpt

### Any log messages given by the failure
```
The required version of the Azure Powershell cmdlets was no
t detected. We recommend that you follow the
    instructions on https://docs.microsoft.com/en-us/powers
hell/azure/overview?view=azurermps-6.8.1 to update to a compatible version.At /home/user/upgrade.ps1:64 char:5
+     throw "The required version of the Azure Powershell cmdlets was n ...
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : OperationStopped: (The required ve...atible version.:String) [], RuntimeException
+ FullyQualifiedErrorId : The required version of the Azure Powershell cmdlets was not detected. We recommend that you follow the
    instructions on https://docs.microsoft.com/en-us/powershell/azure/overview?view=azurermps-6.8.1 to update to a compatible version.
```
### Expected/desired behavior
Would expect a successful upgrade

### OS and Version?
Azure Cloudshell

### Versions
>

### Mention any other details that might be useful
The error log output and code indicate that this script is looking for specific versions of the AzureRM module. (6.8.1) The Azure Cloudshell Modules have different version numbers. I am not sure if the functionality of the "NetCore" versions of the modules will provide different outcomes.
> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by ali92hm** [comment]
Hi there,

Thanks for reporting this issue. We've noticed this problem and posted updated instructions [here](https://github.com/Azure-Samples/blockchain/tree/master/blockchain-workbench/scripts/upgrade). 

We are working with the CloudShell team to bring the cloud shell upgrade back.
