### ISSUE TITLE
Solidity function returning parameters configuration

### ISSUE THREAD

**Issue by CarlosLanderas** [Azure-Samples/blockchain#58]
Hi, I am looking to the different samples available in this repository and I can't see any json configuration with workflow functions returning parameters

For example:
```solidity
function myFunction(string param1) public view returns (uint, uint);
```
Is this scenario **not supported yet** on Azure Blockchain Workbench?.

If I change the method signature to:

```solidity
function myFunction(string param1) public;
```

The error that I am getting in Azure when uploading my contract actually dissapears like the modified signature is what the workbench is looking for, without return parameters.

If this feature is not available yet, is it on the roadmap for the next version?

Thank you very much

**Comment by brendalee** [comment]
Hi Carlos, thanks for using Workbench! That scenario isn't supported yet on Workbench but it is in our backlog. Do you mind sharing the scenario you're looking at?

**Comment by CarlosLanderas** [comment]
Hello, imagine a dynamic smart contract that is a voting poll where you can add different questions and different answers per question:

```solidity
function addQuestion(string description) public  
```
```solidity
function addAnswer(uint questionId, string description) public 
```

User could vote, throught a rich UI the different questions using:

```solidity
function vote(uint questionId, uint answerId) public
```
As all questions are dynamic and can have different answers you need to use mappings:

For example:

```solidity
  mapping(uint => Answer[]) questionAnswers;
  mapping(address => VoterAnswer[]) votersAnswers;
```

As I can not mantain the state on properties that can be accessed by workbench (primitives) I need to have a mechanism to retrieve the user votes per question:

```solidity
 function getUserVote(address addr, uint index) public view returns (uint, uint)
```

I think it would be great if you can declare returning parameters on function sections in the json configuration file. If you see the library [NEthereum](https://github.com/Nethereum/Nethereum) they bind 
returning parameters from functions using type declarations and in this scenario the workbench api could return dynamic values.

In my opinion this would allow creating richest smart contracts, it is really good to know that you have this on the roadmap.

Thank you very much.

**Comment by brendalee** [comment]
Thanks for sharing - this feature is on our backlog. You can visit https://aka.ms/blockchainuservoice to input feature requests and upvote other features as well.
