### ISSUE TITLE
Is the source for Azure blockchain workbench going to be released as opensource?

### ISSUE THREAD

**Issue by mikedennis** [Azure-Samples/blockchain#6]
Just wondering if the source code for the AppServices and/or the worker microservices are going to be released as opensource? It looks like this is just going to be a repository of samples.

There is a lot of blackbox going on behind the scenes which would be nice to see what exactly it's doing.

**Comment by mmercuri** [comment]
There's nothing to announce at this time. 

There are open APIs for REST and Messaging and a set of DB views that are the primary interfaces.   

There is an architecture diagram that discusses what the pieces are and what they do in the documentation. If you'd like to go deeper, let us know and we can look at doing a webcast or similar.

If there are particular questions you have please feel free to message me.

**Comment by jeffryvu** [comment]
I would definitely be interested in going deeper on a webcast.

**Comment by mikedennis** [comment]
@mmercuri Definitely interested in a deep dive and I do have some specific questions. What is the best way to contact you? My email address is in my github profile if you can send me contact information.
