### ISSUE TITLE
Workbench UI Take action button is disabled when enum declared in function signature

### ISSUE THREAD

**Issue by CarlosLanderas** [Azure-Samples/blockchain#61]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
> Create a function with the following signature:

```solidity
enum AnswerType { No, Yes}

function vote(uint questionIndex, AnswerType answer) public {
```

Configure the function and declare its parameters:

```json
 "Parameters": [
                        {
                            "Name": "questionIndex",
                            "Description": "Question number",
                            "DisplayName": "Question number",
                            "Type": {
                                "Name": "int"
                            }
                        },
                        {
                            "Name": "answer",
                            "Description": "Selected question option",
                            "DisplayName": "Answer to the question",
                            "Type": {
                                "Name": "enum",
                                "EnumValues": ["No", "Yes"]                                
                            }
                        }
```

Create the application on the Workbench UI app and you won't be able to trigger the Take Action button. All data is correct but the button will remain disabled

![UI error](https://preview.ibb.co/hUcqXf/Capture.png)

### Any log messages given by the failure
>

### Expected/desired behavior
> When all data types validations are passed on the UI you must be able to trigger the action.

**Note**: I guess this is a UI related bug as triggering the function throught the REST api works like a charm.

### OS and Version?
> Windows 7, 8 or 10. Linux (which distribution). macOS (Yosemite? El Capitan? Sierra?)

### Versions
>

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by brendalee** [comment]
Thanks for reporting! This is fixed for the next Workbench release.
