### ISSUE TITLE
bearer-token sample docker code broken

### ISSUE THREAD

**Issue by larryms** [Azure-Samples/blockchain#77]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [ x] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
>

### Any log messages given by the failure
>

### Expected/desired behavior
>

### OS and Version?
> Windows 7, 8 or 10. Linux (which distribution). macOS (Yosemite? El Capitan? Sierra?)

### Versions
>

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

see pr #76

**Comment by larryms** [comment]
docker node.js code was broken.  fixed dockerfile and package.json file.  see pr #76

**Comment by ali92hm** [comment]
Hi, 

We've deprecated the bearer-token-retrieval sample. Please use the [Postman User](https://github.com/Azure-Samples/blockchain/tree/master/blockchain-workbench/auth-samples/postman-user)
