### ISSUE TITLE
URL broken for FrequentFlyerRewardsCalculator.zip

### ISSUE THREAD

**Issue by cheahengsoon** [Azure-Samples/blockchain#83]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
- [X] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
> URL broken for FrequentFlyerRewardsCalculator.zip

### Any log messages given by the failure
>

### Expected/desired behavior
>

### OS and Version?
> Windows 7, 8 or 10. Linux (which distribution). macOS (Yosemite? El Capitan? Sierra?)

### Versions
>

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by XinxingLiu** [comment]
Thanks for your feedback! Could you specify the reproduce steps in more details? Which URL you are talking about? Thanks!

**Comment by cheahengsoon** [comment]
> Thanks for your feedback! Could you specify the reproduce steps in more details? Which URL you are talking about? Thanks!

https://github.com/Azure-Samples/blockchain/blob/master/blockchain-workbench/application-and-smart-contract-samples/frequent-flyer-rewards-calculator/ethereum/FrequentFlyerRewardsCalculator.zip

**Comment by qishangg** [comment]
FrequentFlyerRewardsCalculator.zip has been deleted in Oct.  Please reference to json and sol file.

**Comment by brendalee** [comment]
Docs updated.
