### ISSUE TITLE
Wrong Open Api definition in /api/v1/contracts/{contractId}/actions

### ISSUE THREAD

**Issue by CarlosLanderas** [Azure-Samples/blockchain#88]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

Hello, I have generated a C# client for the Azure Workbench Api using Nswag and I am having trouble when calling
/api/v1/contracts/{contractId}/actions endpoint

The swagger.json description specifies that this endpoint returns a type called **WorkflowStateTransitionList** with a  json property called "workflowStateTransitions" but it is actually returning a property called "**workflowFunctions**" that represents a different type so autogenerated clients can't deserialize the response properly.

**Comment by iwooden** [comment]
Thanks, will track swagger updates in your other issue #89
