### ISSUE TITLE
Missing queue for IOT/Blockchain integration

### ISSUE THREAD

**Issue by rulopotamo** [Azure-Samples/blockchain#91]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
- [x ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
>When creating Logic App for consuming messages from the IoT Hub into the Blockchain Workbench environment, I can't find a queue called "activityhub" in the workbench deployment, so it is not possible to complete the "for-each" action of the logic app.

### Expected/desired behavior
> We need the name of the queue in the workbench environment that consumes the telemetry from the iot hub.

### OS and Version?
> Azure portal

**Comment by brendalee** [comment]
it should be called ingressQueue. Thanks for bringing this up, we will update the docs.
