### ISSUE TITLE
Unable to update chaincode state in Refrigerated Transportation Sample

### ISSUE THREAD

**Issue by jiahaoc1993** [Azure-Samples/blockchain#93]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
> I went through the [IOT integration document](https://github.com/Azure-Samples/blockchain/blob/master/blockchain-workbench/iot-integration-samples/ConfigureIoTDemo.md) and now I have an `IOT HUB` to handle my devices and their message, the `Logic App`  is also worked well, I can see the data from `IOT HUB` are parsed and then sent to `Service BUS(ingressQueue as the document said)`, however, not any state was updated of the Refrigerated Transportation Contract.

### Any log messages given by the failure
>  I think the DLT consumer log would be helpful, but I don't know where they are.

### Expected/desired behavior
> State update could be tracked on the Workbench app web page

### OS and Version?
> Windows 7, 8 or 10. Linux (which distribution). macOS (Yosemite? El Capitan? Sierra?)

### Versions
> 1.5

### Mention any other details that might be useful

> If I log as the `Device` role on Blockchain Workbench app web page and perform the 'IngestTelemetry' function, the state could be updated correctly.

> Thanks! We'll be in touch soon.

**Comment by iwooden** [comment]
Hi,

As part of your Workbench deployment you should have an OMS instance that will provide logs generated by the various Workbench components, including the DLT consumer (called "eth-watcher"). You can search for the transaction hash of your action to see if it was processed correctly by the watcher.

You can get the transaction hash either through updates posted to Service Bus (in the ingressQueue), or by clicking on the action in the Workbench web UI.

Usually if you have an instance where the transaction was successfully submitted and processed but didn't result in a state change, it's indicative of an error in the smart contract. Please make sure that your IOT Hub has a user assigned within Workbench and that the user has the correct role assigned for the contract.
