### ISSUE TITLE
Invalid messaging integration sample

### ISSUE THREAD

**Issue by SaebAmini** [Azure-Samples/blockchain#98]
### This issue is for a:
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
- [x] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
Follow the sample from: https://github.com/Azure-Samples/blockchain/blob/master/blockchain-workbench/messaging-integration-samples/CreateContract.md

Towards the end, it creates a logic app action that gets data from `LogicAppGetContractCreationDetails`, and suggests setting the `userChainIdentifier` from that data. However, the [stored procedure](https://github.com/Azure-Samples/blockchain/blob/8ee4e0da6bc8920e9c9a1a2efda64b8cba3eed1d/blockchain-workbench/messaging-integration-samples/SQL/LogicAppStoredProcedures.sql#L39) does not return that bit of data at all.

Also, the screenshot from earlier suggests that the stored proc would take an extra `EmailAddress` argument, while it only has two:

![](https://raw.githubusercontent.com/Azure-Samples/blockchain/master/blockchain-workbench/messaging-integration-samples/media/ef7bc4d025f9bfa747b75123cac778f1.png)

**Comment by rich0505** [comment]
There is a screen shot "Execute Stored Procedure 2", which will run LogicAppGetUserChainIdentifierFromName to get userChainIdentifier.

You can close this issue if that works for you.

**Comment by SaebAmini** [comment]
Noticed the screenshot, a bit obscure so maybe a good idea to add some notes about adding that as well. Currently the guide only mentions `LogicAppGetContractCreationDetails`.

However even with that, as per the screenshot above, it's saying the `LogicAppGetContractCreationDetails` takes an extra EmailAddress argument, while it only takes two, `ApplicationName` and `WorkflowName`.

**Comment by rich0505** [comment]
You're right, the documentation does not match the stored procedure. 
We will fix the documentation issue. Meanwhile, are you able to run the sample successfully or are you blocked by the inaccurate documentation?

**Comment by SaebAmini** [comment]
I've just been trying to understand various ways of integrating/extending the workbench so I'm not blocked, I was just reading through them and noticed and logged this issue.

**Comment by ramyapradhan** [comment]
Hello @SaebAmini, thank you for pointing this out.  We have a work item tracking this issue and so will be closing it here.  Please let us know if there is any other thing that we can help with.

Thank you!
